apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-selfsigned
  namespace: cliente-default-gateway
spec:
  isCA: true
  commonName: cert-selfsigned-ca
  secretName: cert-selfsigned-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
