apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: cliente-default-gateway
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: nginx
  sessionAffinity: None
