apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: cliente-default-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        # ------------------------------------
        # --> NGINX
        # ------------------------------------
        - name: nginx
          image: nginx:stable-alpine
          imagePullPolicy: IfNotPresent

          resources:
            limits:
              memory: "128Mi"
              cpu: "10m"

          ports:
          - containerPort: 443
            name: https
            protocol: TCP

          volumeMounts:
          - name: nginx
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
            readOnly: true
          - name: nginx
            mountPath: /var/www/html/index.html
            subPath: index.html
            readOnly: true
          - name: certificate-selfsigned
            mountPath: /etc/nginx/ssl
            readOnly: true

          livenessProbe:
            httpGet:
              path: /
              port: 443
              scheme: HTTPS
            periodSeconds: 30
            failureThreshold: 3
            initialDelaySeconds: 30
            timeoutSeconds: 10

      volumes:
      - name: nginx
        configMap:
          name: nginx
      - name: certificate-selfsigned
        secret:
          secretName: cert-selfsigned-secret
