apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: cliente-default-gateway
data:
  default.conf: |
    server {
        listen 443 ssl;
        server_name  _;
        index index.html;
        root /var/www/html;

        ssl_certificate       ssl/tls.crt;
        ssl_certificate_key   ssl/tls.key;
    }
  index.html: |
    <pre>internal server</pre>